***NUMPY***

numpy is a open source library that contains scientific calculations.

why numpy over list?

--it has more scientific functionalitites than a list.

--it has more ai handling function

--stores all data in array format which accepts only one type of data which reduces memory  and time utilization

--import numpy as np

To convert list into numpy array:
  array_name=np.array(listname)


In [1]:
import numpy as np
a=[1,2,3,4]
type(a)
b=np.array(a)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

CREATE USER DEFINED ARRAY:


In [2]:
a=[]
size=int(input("enter size"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
b=np.array(a)
print(b)

enter size 4
enter number 4
enter number 5
enter number 6
enter number 7


[4 5 6 7]


**SHAPE,SIZE AND DIMENSION OF ARRAY:**

shape: arrayname.shape

size:arrayname.size

dimension:arrayname.ndim

when number of rows=number of columns it is symmetric matrix

when number of rows!=number of columns it is asymmetric matrix

In [5]:
a=np.array([1,2,3,4])
print(a)
print('shape=',a.shape)
print('size=',a.size)
print('dimension=',a.ndim)

[1 2 3 4]
shape= (4,)
size= 4
dimension= 1


In [7]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print('shape=',a.shape)
print('size=',a.size)
print('dimension=',a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape= (3, 4)
size= 12
dimension= 2


**PRE DEFINED FUNCTIONS IN MUMPY:**

1) np.zeros(size) gives an array in which all values are zero.

2) np.ones(size) gives an array with all values 1.

3) np.eye(size) will create an array in which all diagonal positional elements are 1 and rest are 0.

4) np.diag([values]) will customize our diagonal positional values.

5) RANDOM MODULE=

 --randint() will create and array in a range.

 syntax:np.random.randint(min,max,no.of elements)

 --rand() will create and array in range 0 to 1.

 syntax:np.random.rand(size)

 --randn()will create an array with range -3 to 3

 syntax:np.random.randn(size)

 --seed() will fix our random number.

 syntax:np.random.seed(any pass value)
        np.random.rand(size)



In [10]:
a=np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


In [12]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [24]:
a=np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


In [16]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
a=np.random.randint(1,10,3)
print(a)


[5 6 9]


In [22]:
a=np.random.rand(5)
print(a)

[0.14615369 0.5212124  0.42923753 0.97569678 0.52794764]


In [26]:
a=np.random.randn(5)
print(a)

[ 0.38974263 -0.38249473  0.23512551  0.62226717  0.29763839]


In [28]:
np.random.seed(1)
a=np.random.randint(1,10,3)
print(a)

[6 9 6]


**VIEW VS COPY**

view means modification in original file

copy means modification in duplicated file

In [31]:
a=np.array([1,2,3,4])
b=a[1:3]
b[:]=0
b
a #changes done in original file too

array([1, 0, 0, 4])

In [33]:
a=np.array([1,2,3,4])
b=a[1:3].copy()
b[:]=0
print(b)
print(a) #changes not in done in original file

[0 0]
[1 2 3 4]


**LINE SPACE**

returns same gap numbers from minimum number to maximum number.

syntax:(min,max,number of elements)

In [36]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


**RESHAPING THE ARRAY**

syntax:arrayname.reshape()

to reshape n(rows)x n(column)=n(total elements)

In [49]:
a=np.random.randint(1,30,12)
print(a)
a.reshape(3,4)

[ 6 19 21 12 29 11 29 15 19  5 24 24]


array([[ 6, 19, 21, 12],
       [29, 11, 29, 15],
       [19,  5, 24, 24]])

In [51]:
a.reshape(2,6)

array([[ 6, 19, 21, 12, 29, 11],
       [29, 15, 19,  5, 24, 24]])

In [53]:
a=np.array([1,2,3,4]).reshape(2,2)
print(a)

[[1 2]
 [3 4]]


**ARITHMATIC OPERATIONS:**

In [56]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
print(a+b)
print(a-b)
print(a*b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


**UNIQUE ELEMENT**

returns the unique element in the array

In [59]:
a=np.array([1,2,3,4,1,2,3,4])
print(np.unique(a))

[1 2 3 4]


**STACKING**

a) .hstack()=combines twomatrices horizontally

b) .vstack()=combines two matrices vertically

dimensions should be equal of arrays

In [62]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
print(np.hstack((a,b,c)))
print(np.vstack((a,b,c)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
